name: test
run-name: ${{ github.actor }} runs test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up a Git safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Set up Python
        with:
          python-version: '3.12.x'
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run review
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: poetry run python run_gemini.py
