name: test
run-name: ${{ github.actor }} runs test
on:
  pull_request:
    types: [opened]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run review
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}
          PR_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
          PR_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          BASE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
        run: poetry run python create_pr_comments.py
